name 'test-databag'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures test-databag'
long_description 'Installs/Configures test-databag'
version '0.1.0'
